version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "9000:9000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        image: php:fpm
        volumes:
            - ./app:/app