version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "9000:9000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        image: php:fpm
        build: .
        volumes:
            - ./app:/app
        depends_on: 
            - mysql
    mysql:
        image: yobasystems/alpine-mariadb:latest
        ports:
            - "9001:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=web-asg02
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=13152989Ln@