DROP DATABASE  IF EXISTS WEB_ASG02;
CREATE DATABASE WEB_ASG02;
USE WEB_ASG02;

-- CREAT TABLE TO SAVE INFORMATION CUSTOMER
DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS
(
    CUS_ID    VARCHAR (50),
    FULL_NAME VARCHAR(50)  NOT NULL,
    USERNAME VARCHAR(50)  NOT NULL UNIQUE,
    PASS     VARCHAR(500) NOT NULL,
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (CUS_ID)
);
-- COURSE WILL PROVIDE
DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE
(
    COURSE_NAME VARCHAR(200),
    PRIMARY KEY (COURSE_NAME)

);
-- SUBJECT FOR COURSE
DROP TABLE IF EXISTS SUBJECTS;
CREATE TABLE SUBJECTS
(
    SUB_ID     INT,
    SUB_NAME   VARCHAR(300)  NOT NULL UNIQUE,
    IMAGE     VARCHAR(100),
    INTRO     VARCHAR(1000) NOT NULL,
    START_TIME DATE          NOT NULL,
    TIMELINE  INT           NOT NULL,
    CNAME     VARCHAR(200) NOT NULL,
    PRIMARY KEY (SUB_ID)
);

-- LESSON FOR SUBJECT
DROP TABLE IF EXISTS LESSON;
CREATE TABLE LESSON
(
    ID      INT,
    VIDEO   VARCHAR(500) NOT NULL,
    CONTENT VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);
-- EACH LESSON HAVE A TEST
DROP  TABLE IF EXISTS TESTS;
CREATE TABLE TESTS
(
    ID       INT PRIMARY KEY ,
    WORK_TIME INT NOT NULL
);
-- --------------------------------------------------------
-- WEAK ENTRIES
-- RESULT FOR A TEST
DROP TABLE  IF EXISTS RESULT;
CREATE TABLE RESULT(
    START_TIME DATETIME,
    END_TIME DATETIME NOT NULL,
    CID VARCHAR (50),
    TEST_ID INT,
    PRIMARY KEY (START_TIME,CID,TEST_ID),
    FOREIGN KEY (CID) REFERENCES CUSTOMERS(CUS_ID)ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (TEST_ID) REFERENCES TESTS(ID) ON DELETE CASCADE  ON UPDATE CASCADE

);
-- ---------------------------------------------------------------------
-- RELATION
-- 1. INCLUDE RELATON
ALTER TABLE SUBJECTS
ADD FOREIGN KEY (CNAME) REFERENCES COURSE(COURSE_NAME) ON DELETE CASCADE  ON UPDATE CASCADE;
-- 2. REG BETWEEN SUBJECT AND CUSTOMER
DROP TABLE IF EXISTS REG_SUBJECT;
CREATE TABLE REG_SUBJECT(
    CUSTOMER_ID VARCHAR (50),
    SUBJECT_ID INT,
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (CUSTOMER_ID,SUBJECT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES  CUSTOMERS(CUS_ID) ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUB_ID) ON DELETE CASCADE  ON UPDATE CASCADE
);
-- 3. SUBJECT HAVE LESSON
ALTER TABLE LESSON ADD COLUMN  SUBJECT_ID INT NOT NULL;
ALTER TABLE LESSON ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUB_ID) ON DELETE CASCADE  ON UPDATE CASCADE;
-- 4. LEARN RELATION AND TIME Multivalued Attribute
DROP TABLE IF EXISTS LEARN;
CREATE TABLE LEARN(
    CUSTOMER VARCHAR(50),
    LESSON INT,
    PRIMARY KEY (CUSTOMER,LESSON),
    FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(CUS_ID) ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (LESSON) REFERENCES LESSON(ID) ON DELETE CASCADE  ON UPDATE CASCADE
);
DROP TABLE IF EXISTS LEARN_TIME;
CREATE TABLE LEARN_TIME (
    CUSTOMER VARCHAR(50),
    LESSON INT,
    START_TIME DATETIME,
    END_TIME DATETIME,
    PRIMARY KEY (CUSTOMER,LESSON,START_TIME,END_TIME),
    FOREIGN KEY (CUSTOMER,LESSON) REFERENCES LEARN(CUSTOMER, LESSON) ON DELETE CASCADE  ON UPDATE CASCADE
);
-- HAVE RELATION TEST AND LESSON
ALTER TABLE TESTS ADD COLUMN LESSON_ID INT NOT NULL UNIQUE ;
ALTER TABLE TESTS ADD FOREIGN KEY (LESSON_ID)  REFERENCES LESSON(ID) ON DELETE CASCADE  ON UPDATE CASCADE;
-- ------------------------------------------------------------------------
-- Multivalued Attribute
-- 1. QUESTION FOR TEST
DROP TABLE IF EXISTS TEST_QUESTION;
CREATE TABLE TEST_QUESTION(
    TEST_ID INT,
    NOS INT,
    CONTENT VARCHAR(500),
    ANSWER VARCHAR(10),
    PRIMARY KEY (TEST_ID, NOS, CONTENT,ANSWER),
    FOREIGN KEY (TEST_ID) REFERENCES TESTS(ID) ON DELETE CASCADE  ON UPDATE CASCADE
);
-- 2. ANSWER FOR RESULT
DROP TABLE IF EXISTS RESULT_ANS;
CREATE TABLE RESULT_ANS(
    START_TIME DATETIME,
    CUS_ID VARCHAR(50),
    TEST_ID INT,
    NOS INT,
    ANS VARCHAR(10),
    PRIMARY KEY (START_TIME,CUS_ID,TEST_ID,NOS,ANS),
    FOREIGN KEY (START_TIME,CUS_ID,TEST_ID) REFERENCES RESULT(START_TIME, CID, TEST_ID) ON DELETE CASCADE  ON UPDATE CASCADE
);
ALTER TABLE CUSTOMERS ADD EMAIL VARCHAR(100) NOT NULL;



